name: Create diagram
on:
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@v0.7.1
        with:
          excluded_paths: "ignore,.github"
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated diagram
          branch: main
          file_pattern: "repo.svg"
